name: Automated Testing

on:
  push:
    branches:
      - '*' # Trigger on any branch push
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test # Adjust the command to run your unit tests

      - name: Run functional tests
        run: npm run functional-test # Adjust the command to run your functional tests

      - name: Run style checks
        run: npm run lint # Adjust the command to run your style checks

